import { Providers } from "./providers";
import MainLayout from "./src/layouts";
import './styles/main.css'

export const metadata = {
  title: "Juna",
  description: "Generated by Juna",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <Providers>
          <MainLayout>{children}</MainLayout>
          {/* <ToastContainer /> */}
        </Providers>
      </body>
    </html>
  );
}
